### ISSUE TITLE
Pattern found in the Cloud SDK version file could not be parsed: 218.0.0.213974472

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-plugins-core#708]
com.google.cloud.tools.appengine.cloudsdk.CloudSdkVersionFileParseException: Pattern found in the Cloud SDK version file could not be parsed: 218.0.0.213974472
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:95)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdkVersion(CloudSdk.java:187)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdk(CloudSdk.java:181)
	at com.google.cloud.tools.appengine.cloudsdk.GcloudRunner.run(GcloudRunner.java:75)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDeployment.deploy(CloudSdkAppEngineDeployment.java:88)
	at com.google.cloud.tools.intellij.appengine.java.cloud.AppEngineDeploy.deploy(AppEngineDeploy.java:152)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardDeployTask.lambda$deploy$0(AppEngineStandardDeployTask.java:126)
	at com.google.cloud.tools.appengine.cloudsdk.process.LegacyProcessHandler.syncRun(LegacyProcessHandler.java:144)
	at com.google.cloud.tools.appengine.cloudsdk.process.LegacyProcessHandler.access$200(LegacyProcessHandler.java:31)
	at com.google.cloud.tools.appengine.cloudsdk.process.LegacyProcessHandler$3.run(LegacyProcessHandler.java:163)
Caused by: java.lang.IllegalArgumentException: Pattern "218.0.0.213974472" is not a valid CloudSdkVersion.
	at com.google.cloud.tools.appengine.cloudsdk.serialization.CloudSdkVersion.<init>(CloudSdkVersion.java:66)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.getVersion(CloudSdk.java:91)
	... 9 more
Exception class name:
java.lang.IllegalArgumentException
Exception message:
Pattern found in the Cloud SDK version file could not be parsed: 218.0.0.213974472
Throw file name:
CloudSdk.java
Throw line number:
95
Throw class name:
com.google.cloud.tools.appengine.cloudsdk.CloudSdk
Throw method name:
getVersion

**Comment by elharo** [comment]
1. 218.0.0.213974472 is not compliant with the semantic versioning specification.
2. We believe this version string shows up in internal, alpha builds of the Cloud SDK.

**Comment by patflynn** [comment]
@loosebazooka can you prioritize this with someone from your team?

It'll be important to work with the clients (especially IDEs) to preserve some level of version feedback in the UX.

**Comment by etanshaul** [comment]
fyi we are tracking the IJ side of things here: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2259

The solution there will probably depend on what we end up doing here in the core lib.

**Comment by elharo** [comment]
To handle anything that could conceivably show up in a VERSION file I think we would need to change this validateCloudSdkVersion  method
so it explicitly catches CloudSdkVersionFileParseException and
responds differently:

private void validateCloudSdkVersion()
throws CloudSdkOutOfDateException, CloudSdkVersionFileException {
try {
CloudSdkVersion version = getVersion();
if (version.compareTo(MINIMUM_VERSION) < 0) {
throw new CloudSdkOutOfDateException(version, MINIMUM_VERSION);
}
} catch (CloudSdkVersionFileNotFoundException ex) {
// this is likely a version of the Cloud SDK prior to when VERSION
files were introduced
throw new CloudSdkOutOfDateException(MINIMUM_VERSION);
}
}

**Comment by aalexand** [comment]
Getting this error as well.

```
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy (default-cli) on project helloworld: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy failed: Pattern found in the Cloud SDK version file could not be parsed: 218.0.0.213974472: Pattern "218.0.0.213974472" is not a valid CloudSdkVersion. -> [Help 1]
```

Using the internal build of Cloud SDK. Can't deploy anything. Is there a fix?

**Comment by aalexand** [comment]
Resorted to use external version of the cloud sdk for now.

**Comment by chanseokoh** [comment]
Try upgrading the internal build of Cloud SDK too. We were told that the problematic version string was a one-off mistake that has been fixed (although I think it's totally possible that this will not be resolved until a new release rolls out). If upgrading doesn't do anything and you must use the internal version for some reason, open the `VERSION` file in the Cloud SDK root directory, drop the `.213974472` part from `218.0.0.213974472`, and save it.
