### ISSUE TITLE
Test failure: cannot reach: https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/bigquery/package-summary.html

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#712]
Oddly, it returns 404 briefly and redirects to

https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/bigquery/package-summary.html

Maybe we should change the URL to the new redirection.

```
java.lang.AssertionError: Could not reach https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/bigquery/package-summary.html expected:<200> but was:<404>
	at com.google.cloud.tools.libraries.LibrariesTest.assertReachable(LibrariesTest.java:117)
	at com.google.cloud.tools.libraries.LibrariesTest.assertApi(LibrariesTest.java:92)
	at com.google.cloud.tools.libraries.LibrariesTest.testJson(LibrariesTest.java:58)
```

**Comment by chanseokoh** [comment]
Oh, seems like this will be fixed by #710.
