### ISSUE TITLE
Kokoro Windows test fails when installing latest managed Cloud SDK

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-plugins-core#851]
`google-cloud-sdk-286.0.0-windows-x86_64-bundled-python.zip` seems to be working while `google-cloud-sdk-windows-x86_64-bundled-python.zip` (i.e., the latest) doesn't.

On Kokoro, the install script (`install.bat`) ends up using `c:\python27\python.exe`. Kokoro may have Python 3, and we might be able to force that with an environment variable for the latest gcloud version test? Or, maybe it's more meaningful to delete `c:\python27\python.exe` on Kokoro, so that we verify installing Cloud SDK using the bundled Python.

```
[INFO] Running com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest
Nov 12, 2020 8:41:35 AM com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk getOsSpecificManagedSdkHome
WARNING: LOCALAPPDATA environment is invalid or missing
Nov 12, 2020 8:41:35 AM com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk getOsSpecificManagedSdkHome
WARNING: T:\tmp\junit2803105313849379831\AppData\Local does not exist
Nov 12, 2020 8:41:35 AM com.google.cloud.tools.managedcloudsdk.install.Downloader download
INFO: Downloading https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-286.0.0-windows-x86_64-bundled-python.zip to T:\tmp\junit7934090192523661365\downloads\google-cloud-sdk-286.0.0-windows-x86_64-bundled-python.zip
Nov 12, 2020 8:42:57 AM com.google.cloud.tools.managedcloudsdk.ManagedCloudSdk getOsSpecificManagedSdkHome
WARNING: T:\tmp\junit4915690960182035097\Library\Application Support does not exist
Nov 12, 2020 8:42:57 AM com.google.cloud.tools.managedcloudsdk.install.Downloader download
INFO: Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk-windows-x86_64-bundled-python.zip to T:\tmp\junit2306234316261850375\downloads\google-cloud-sdk-windows-x86_64-bundled-python.zip
testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)
Welcome to the Google Cloud SDK!
Active code page: 65001
ERROR: gcloud failed to load: To run PySocks on Windows you must install win_inet_pton
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
    from googlecloudsdk.api_lib.util import apis_internal
    from googlecloudsdk.core import properties
    from googlecloudsdk.core.util import http_proxy_types
    import socks
    "To run PySocks on Windows you must install win_inet_pton")

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 or 3.5+ executable:
    c:\python27\python.exe

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 or 3.5+ executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
Traceback (most recent call last):
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\\bin\bootstrapping\install.py", line 12, in <module>
    import bootstrapping
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 40, in <module>
    from googlecloudsdk.core import execution_utils
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\lib\googlecloudsdk\core\execution_utils.py", line 36, in <module>
    from googlecloudsdk.core import log
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\lib\googlecloudsdk\core\log.py", line 33, in <module>
    from googlecloudsdk.core import properties
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\lib\googlecloudsdk\core\properties.py", line 34, in <module>
    from googlecloudsdk.core.util import http_proxy_types
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\lib\googlecloudsdk\core\util\http_proxy_types.py", line 22, in <module>
    import socks
  File "T:\tmp\junit2306234316261850375\LATEST\google-cloud-sdk\lib\third_party\socks\__init__.py", line 24, in <module>
    "To run PySocks on Windows you must install win_inet_pton")
ImportError: To run PySocks on Windows you must install win_inet_pton
Active code page: 437

[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 100.063 s <<< FAILURE! - in com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest
[ERROR] testManagedCloudSdk_latest(com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest)  Time elapsed: 17.469 s  <<< ERROR!
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.ManagedCloudSdkTest.testManagedCloudSdk_latest(ManagedCloudSdkTest.java:117)
```

**Comment by loosebazooka** [comment]
It would probably result in a similar failure on user's machines? Maybe the cloud sdk team has some insight? @vilasj

**Comment by chanseokoh** [comment]
#852 will unblock the failure, but I agree this will probably manifest on the user's machine too.

**Comment by chanseokoh** [comment]
Easily reproducible on Kokoro Windows.
```bat
call curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk-windows-x86_64-bundled-python.zip
call unzip google-cloud-sdk-windows-x86_64-bundled-python.zip
call cmd.exe /c T:\tmp\google-cloud-sdk\install.bat
```

Log: 
```
T:\tmp>call cmd.exe /c T:\tmp\google-cloud-sdk\install.bat 
Welcome to the Google Cloud SDK!
Active code page: 65001
ERROR: gcloud failed to load: To run PySocks on Windows you must install win_inet_pton
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
    from googlecloudsdk.api_lib.util import apis_internal
    from googlecloudsdk.core import properties
    from googlecloudsdk.core.util import http_proxy_types
    import socks
    "To run PySocks on Windows you must install win_inet_pton")

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 or 3.5+ executable:
    c:\python27\python.exe

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 or 3.5+ executable.
```

**Comment by chanseokoh** [comment]
b/173607938

For an immediate fix, what the Cloud SDK team suggests for automation:
```
cmd /c "<installer path>\GoogleCloudSDKInstaller.exe /S /noreporting /nostartmenu /nodesktop /logtofile /sdkurl "...\google-cloud-sdk-windows-x86_64-bundled-python.zip" /D=%CLOUDSDK_INSTALL_PATH%"
```
